#!/usr/bin/env python

import os
from diffusers import DiffusionPipeline


MODEL_ID = "timbrooks/instruct-pix2pix"
MODEL_CACHE = "diffusers-cache"

os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = DiffusionPipeline.from_pretrained(
    MODEL_ID,
    cache_dir=MODEL_CACHE,
)
